### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by wf58585858** [zlq4863947/triangular-arbitrage2#2]
┌─[root@centos7-dev-7] - [/var/node/py_demo1] - [2021-06-12 06:27:42]
└─[0] <git:(main 2daefbc) > npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Invalid version: "1.0"
npm WARN py_demo1 No description
npm WARN py_demo1 No repository field.
npm WARN py_demo1 No README data
npm WARN py_demo1 No license field.

up to date in 0.874s
found 0 vulnerabilities

┌─[root@centos7-dev-7] - [/var/node/py_demo1] - [2021-06-12 06:29:05]
└─[0] <git:(main 2daefbc✈) > npm start
npm ERR! Invalid version: "1.0"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-12T10_29_27_663Z-debug.log

**Comment by zlq4863947** [comment]
不要用npm， 用yarn
